---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-docstring-first
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
  - id: check-added-large-files
  - id: debug-statements
- repo: https://github.com/asottile/pyupgrade
  rev: v3.9.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.5
  hooks:
  - id: pycln
    args: [--all]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.10.0
  hooks:
  - id: reorder-python-imports
    args: [--py310-plus]
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==22.8.23]
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-use-type-annotations
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - id: mypy
