PROJECTDIR = ../../..
DIRS =\
	senscord_source\
	inference_wasi_nn\
	ppl_detection_ssd\
	draw_bboxes\
	senscord_sink

export TOOL=wasi
export BINDIR=../bin
include $(PROJECTDIR)/scripts/rules.mk

all: $(DIRS)
